package:
  name: ksh
  version: 1.0.10
  epoch: 1
  description: "KornShell 93u+m"
  copyright:
    - license: EPL-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ksh93/ksh
      tag: v${{package.version}}
      expected-commit: f0999ab76dd2e0d977298348ec5c4535a360710d

  - runs: |
      bin/package make
      bin/package install ${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: ksh93/ksh
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        ksh --version
        ksh --help